spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_crm
    username: root
    password: kfy602211
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-provider
logging:
  level:
    cn.itcast: debug

  mybatis:
   mapper-locations=classpath: mappers/*.xml
   type-aliases-package: cn.itcast.pojo
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka
  instance:
    lease-renewal-interval-in-seconds: 30    #心跳
    lease-expiration-duration-in-seconds: 90 #90秒没有心跳就认为服务已经挂了